spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/microservice
  datasource:
    url: postgresql://iblrcnaa:NzSFyMEaa2hAOZ1NJxizLJjXNR8r8pz6@mahmud.db.elephantsql.com/iblrcnaa
    username: iblrcnaa
    password: NzSFyMEaa2hAOZ1NJxizLJjXNR8r8pz6
